Use the GITHUB_TOKEN to avoid exceeding the API rate limit
There was a recent uptick of problems with the `limit-access-to-actor`
feature because it uses an unauthenticated REST API call (and the rate
limiting is based on IP, i.e. hosted GitHub build agents will run into
this _a lot_). The symptom looks like this:

	Error: API rate limit exceeded for 172.176.196.48. (But here's
	the good news: Authenticated requests get a higher rate limit.
	Check out the documentation for more details.)

Let's imitate how `actions/checkout` uses authenticated REST API calls
(see https://github.com/actions/checkout/blob/v3.3.0/action.yml#L24):
add an "input" variable with the correct default (and users are
expected to never _actually_ to provide that variable).

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>